# $Id$

TOP_SRCDIR=..

.PHONY: all check clean doc

all: check

check:
	(cd ${TOP_SRCDIR}; ${MAKE} $@)

clean:
	rm -f *~ helloJsTestDriver.min.js

doc:
	(cd ${TOP_SRCDIR}; ${MAKE} $@)

pack:
	(cd ${TOP_SRCDIR}; ${MAKE} $@)

# EOF
